// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * The whole board, for a front end that has just mounted.
 */
async boardSnapshot() : Promise<Result<BoardSnapshot, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_snapshot") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Moves an awake departure into ACTIVÉS; rejected for anything else.
 */
async activateFlight(callsign: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("activate_flight", { callsign }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async flightDetail(callsign: string) : Promise<Result<FlightDetail | null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("flight_detail", { callsign }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
boardUpdated: BoardUpdated
}>({
boardUpdated: "board-updated"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * The whole board at once, for a front end that has just mounted.
 */
export type BoardSnapshot = { seq: number; columns: Columns; strips: StripView[] }
export type BoardUpdate = { seq: number; columns: Columns | null; upserted: StripView[]; removed: string[] }
/**
 * Coalesced board delta. Emitted at most every `emitIntervalMs`, never once per parsed line.
 */
export type BoardUpdated = BoardUpdate
export type Columns = { awake: string[]; activatedDepartures: string[]; arrivals: string[]; transits: string[] }
/**
 * Everything the activation dialog shows. Deliberately off the high-frequency board stream.
 */
export type FlightDetail = { callsign: string; aircraft: string; wake: string; rules: string; flightType: string; dep: string; arr: string; alternate: string; eobt: string; cruiseLevel: string; route: string; squawk: string; assumedBy: string; stand: string }
export type IpcError = { kind: "notRunning" } | { kind: "unknownCallsign"; message: string } | { kind: "rejected"; message: string }
/**
 * Exactly what one strip renders; everything else the modal fetches on demand.
 */
export type StripView = { callsign: string; adep: string; ades: string; rules: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
