// Every string the controller sees, in French, exactly as in the Figma. Nothing else in the
// front end may hold user-facing text.
export const LABELS = {
  tabs: {
    vigie: "VIGIE",
    ifr: "IFR",
    editeur: "EDITEUR",
    options: "OPTIONS",
  },
  columns: {
    awake: "ÉVEILLÉS",
    activated: "ACTIVÉS",
    transits: "TRANSITS",
  },
  window: {
    navigation: "Onglets",
    minimize: "Réduire",
    maximize: "Agrandir",
    close: "Fermer",
  },
  editor: {
    length: "Longueur",
    width: "Largeur",
    millimetres: "mm",
    name: "Nom du strip",
    save: "SAVE",
    tabFields: "CHAMPS",
    tabDesign: "DESIGN",
    columnName: "Nom",
    columnSize: "Taille",
    columnElement: "Élément",
    add: "Ajouter",
    remove: "Supprimer",
    edit: "Modifier",
    decrease: "Diminuer",
    increase: "Augmenter",
    scrollUp: "Défiler vers le haut",
    scrollDown: "Défiler vers le bas",
    palette: {
      line: "LIGNE",
      frame: "CADRE",
      text: "TEXTE",
      image: "LOGO",
    },
    elementSize: {
      length: "Longueur",
      thickness: "Épaisseur",
      width: "Largeur",
      height: "Hauteur",
      fontSize: "Corps",
      orientation: "Sens",
    },
    orientationShort: {
      horizontal: "H",
      vertical: "V",
      turn: "90°",
    },
    invalid: "Nom invalide",
    nameErrors: {
      empty: "Le nom est vide.",
      wordCount: "Le nom doit contenir quatre mots : OACI POSITION TYPE STRIP.",
      icao: "Code OACI invalide :",
      position: "Position inconnue :",
      kind: "Type de strip inconnu :",
      suffix: "Le nom doit se terminer par STRIP :",
    },
    confirmOverwrite: "Un strip porte déjà ce nom. Le remplacer ?",
    confirmDelete: "Supprimer ce strip définitivement ?",
    confirm: "Confirmer",
    cancel: "Annuler",
    clamped: "Des éléments ont été replacés à l'intérieur du strip.",
    imageThreshold: "L'impression thermique est en noir et blanc : le logo sera converti.",
  },
  activation: {
    title: "Activation",
    aircraft: "Type",
    wake: "Turbulence",
    rules: "Règles",
    flightType: "Nature",
    dep: "Départ",
    arr: "Arrivée",
    alternate: "Dégagement",
    eobt: "EOBT",
    cruiseLevel: "Niveau",
    route: "Route",
    squawk: "Transpondeur",
    assumedBy: "Assuré par",
    stand: "Poste",
    confirm: "Activer",
    cancel: "Annuler",
    loading: "Chargement…",
  },
} as const;
